### ISSUE TITLE
Markdown不支持checkbox语法

### ISSUE THREAD

**Issue by maxhis** [kaeyleo/jekyll-theme-H2O#10]
不支持以下checkbox语法：

```
- [x] 已完成
- [ ] 未完成
```
Github默认是支持的：

- [ ] 未完成
- [ ] 已完成

**Comment by youyefu** [comment]
还不支持 flow ，盼作者添加下

**Comment by tea9** [comment]
![image](https://user-images.githubusercontent.com/39117901/45252889-68d12680-b390-11e8-8def-cf3c55cab471.png)
我的可以啊！ 神奇！
https://tea9.xyz/2018/09/08/test_checkbox.html

**Comment by kaeyleo** [comment]
checkbox语法是支持的
