### ISSUE TITLE
所有图片无法加载

### ISSUE THREAD

**Issue by wallfacertony** [kaeyleo/jekyll-theme-H2O#108]
博客程序放在阿里云的服务器上，
文章中所有的图片均无法加载。
我看了一下生成的html文件，发现地址全用的是 内网ip
我认为可能是启动博客时用的是内网ip造成的。
但是使用外网ip启动会出现一个
* jekyll 3.8.5 | Error:  Cannot assign requested address - bind(2) for 47.93.18.71:9999

请问我应该如何处理?
谢谢😀

我的博客地址: http://wallfacer.tk:9999

**Comment by kaeyleo** [comment]
在配置文件里填上你的域名，参考文档：https://github.com/kaeyleo/jekyll-theme-H2O#%E7%AB%99%E7%82%B9%E4%BF%A1%E6%81%AF
