### ISSUE TITLE
请问如何默认使用黑暗模式

### ISSUE THREAD

**Issue by greatplum** [kaeyleo/jekyll-theme-H2O#110]
如题

**Comment by kaeyleo** [comment]
文档有说明：https://github.com/kaeyleo/jekyll-theme-H2O#%E5%A4%9C%E9%97%B4%E6%A8%A1%E5%BC%8F

**Comment by greatplum** [comment]
我的意思是主题换成黑暗模式，不是蓝色或者粉色，还是很感谢你的项目

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
发件人: 悟空 <notifications@github.com>
发送时间: 星期一, 四月 22, 2019 13:47
收件人: kaeyleo/jekyll-theme-H2O
抄送: 李浩; Author
主题: Re: [kaeyleo/jekyll-theme-H2O] 请问如何默认使用黑暗模式 (#110)


Closed #110<https://github.com/kaeyleo/jekyll-theme-H2O/issues/110>.

―

**Comment by kaeyleo** [comment]
@greatplum 没有黑暗主题，只有夜间模式。。
