### ISSUE TITLE
如何新建一个菜单栏关于ABOUT的html的配置

### ISSUE THREAD

**Issue by geekgitcode** [kaeyleo/jekyll-theme-H2O#126]

**Comment by JMbaozi** [comment]
不知道你解决了没有。
* 这是我的效果：https://jmbaozi.top/about.html
* 这是写法：https://github.com/JMbaozi/JMbaozi.github.io/blob/master/about.html
* 在_config.yml文件的nav中加入``` about: '/about.html'```

**Comment by geekgitcode** [comment]
谢谢！
