### ISSUE TITLE
搜索栏右下角有一小块区域有问题

### ISSUE THREAD

**Issue by Songkc** [kaeyleo/jekyll-theme-H2O#16]
如图：
![search](https://user-images.githubusercontent.com/19513583/30117908-32a10ea2-9354-11e7-93ba-c1f4155bef77.jpg)

**Comment by kaeyleo** [comment]
能否说一下是什么操作系统、浏览器呢？

**Comment by Songkc** [comment]
macOS  Chrome
在日间模式下不会有，在夜间模式才会出现

**Comment by Songkc** [comment]
macOS  Chrome
这几天都有出现过，所以提了出来
现在又测试了一下，似乎又不会了😂

**Comment by kaeyleo** [comment]
我目前还没有发现有这个问题，不过感谢提issue啊 👍
