### ISSUE TITLE
gems:[jekyll-paginate]

### ISSUE THREAD

**Issue by lizhifeng-sky** [kaeyleo/jekyll-theme-H2O#17]
C:\Users\Administrator\Desktop\jekyll_demo\jekyll-theme-H2O>jekyll server
jekyll 3.5.2 | Error:  (C:/Users/Administrator/Desktop/jekyll_demo/jekyll-theme-H2O/_config.yml): could not find expected ':' while scanning a simple key at line 64 column 1
line64 是 gems: [jekyll-paginate]

**Comment by lizhifeng-sky** [comment]
第一次装  不知道咋回事

**Comment by kaeyleo** [comment]
H2O主题的Jekyll版本是3.2，3.5版本的gems需要改成plugins。

这样：plugins: [jekyll-paginate]
