### ISSUE TITLE
關於 baseurl 部署的問題

### ISSUE THREAD

**Issue by bananaappletw** [kaeyleo/jekyll-theme-H2O#18]
你好
感謝樓主提供這個主題
最近有使用了一下
感覺相當美觀
後來發覺部署的時候會有個問題 (直接使用 github build from master branch)
就是 `site.baseurl` 的值會變成空的
導致一些頁面無法正常顯示
和[這個 issue](https://github.com/github/pages-gem/issues/350) 有關
也找到了一些修正方法
repo 如下: https://github.com/bamboofox/bamboofox.github.io
把 `_config.yml` 裡的 baseurl: '/' => ''
`"{{site.baseurl}}"` => `"/{{site.baseurl}}"`
如果有確認這問題
看要不要我發個 pull request 來改一下
這樣以後就不會有人遇到這問題
如有說錯請指正我
感謝你

**Comment by kaeyleo** [comment]
Bamboofox很赞！👍
谢谢你们使用H2O主题
确实很多人都遇到了 `site.baseurl` 失效这个问题，我暂时也没时间弄
欢迎提PR，谢谢啦～
