### ISSUE TITLE
ghost-theme-H2O Ghost移植版

### ISSUE THREAD

**Issue by eastpiger** [kaeyleo/jekyll-theme-H2O#24]
Hi

你的这个项目很棒，代码结构也很不错。我把这个project移植到了Ghost站点引擎上，[项目在此](https://github.com/eastpiger/ghost-theme-H2O)。

希望可以项目互链一下。

**Comment by kaeyleo** [comment]
很赞！

**Comment by kaeyleo** [comment]
@eastpiger 已在 README.md 增加该项目链接，感谢移植到Ghost
