### ISSUE TITLE
出现双层代码高亮框

### ISSUE THREAD

**Issue by 740291272** [kaeyleo/jekyll-theme-H2O#27]
![1](https://user-images.githubusercontent.com/12003087/32156284-60270ea6-bd77-11e7-9b50-23da273ac326.png)

**Comment by kaeyleo** [comment]
对应的Markdown发我看一下呢

**Comment by OAlienO** [comment]
在 github page 才會出現
就是普通的代碼區塊(三個 反單引號)

**Comment by Townwang** [comment]
我也出现那个问题了,不过已经改了, 是Markdown的css原因 可以隐藏一下 效果看看我博客 townwang.com

**Comment by pickou** [comment]
@Townwang 请教一下如何解决这个问题

**Comment by Townwang** [comment]
@pickou 在容器外面再嵌套一层 overflow:hidde

**Comment by pickou** [comment]
@Townwang 折腾了一下，不知道在哪里改，对网站一窍不通，是修改prism.js嘛?原谅无知小白

**Comment by sctop** [comment]
去liaokeyu.com上面翻源代码，把css和js给替换了。。我就是这样子干的。。

**Comment by Townwang** [comment]
@pickou 修改css 在代码框的容器外面再嵌套一层 overflow:hidde

**Comment by sctop** [comment]
@Townwang 话说什么是“容器外面”。。。

**Comment by Townwang** [comment]
@sctop div啊  css一对div就是个容器 盒子.......

**Comment by pickou** [comment]
@sctop 这个机智啊。

**Comment by pickou** [comment]
@sctop 我替换了还是原样啊，还是没变化啊。

**Comment by pickou** [comment]
我的解决方案是只用prism来显示，把_config.yml中的highlighter设置为none，也就是不用rouge来解析。然后配色和支持的语言可以从http://prismjs.com/download.html 这个网站选择下载。暂时没什么问题出现

**Comment by sctop** [comment]
Duplicate of #44

**Comment by Famine-Life** [comment]
> @Townwang折腾了一下，不知道在哪里改，对网站一窍不通，是修改prism.js嘛？原谅无知小白

在assets/css下，修改app.min.css文件（如果你的也是的话），修改内容：ctrl+f 查找: **.markdownbody .highlight** ，**修改其{}内的overflow: scroll为overflow:auto或者overflow:hidden**，，如果不确定是不是这个文件的话，F12下查找样式来源，可以找出样式来自哪个文件！ 

END
