### ISSUE TITLE
关于kramdown的问题

### ISSUE THREAD

**Issue by blackhat-cat** [kaeyleo/jekyll-theme-H2O#29]
官方发来邮件说“You are currently using the 'kramdown`' Markdown engine, which is no longer supported by GitHub Pages and may cease working at any time”
要怎么解决？

**Comment by kaeyleo** [comment]
Kramdown这个markdown解析器不再被Github Pages支持了，官方邮件有说明说处理方法的，仔细看看吧。

P.S. 这是之前官方的处理方法：https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/，可参考相关issue: https://github.com/babel/website/issues/709
