### ISSUE TITLE
样式显示异常，下载本地Jekyll预览OK，但是推到GitHub就显示异常，直接fork也是显示异常

### ISSUE THREAD

**Issue by zhangfeidev** [kaeyleo/jekyll-theme-H2O#33]
<img width="1271" alt="2017-11-15 7 36 07" src="https://user-images.githubusercontent.com/12770230/32834128-6276d41c-ca3c-11e7-8d12-2d44f27d592a.png">

**Comment by crisiscain** [comment]
我也这样 请问解决了吗

**Comment by kaeyleo** [comment]
这种情况大多是路径错误，导致无法正确加载样式文件，最终导致所谓的显示异常。
解决方案的话，打开浏览器的检查模式看报错信息，可能会出现相关的url地址，再根据项目结构的目录 和 _includes文件夹里的head.html中的<link>的路径，去修改成正确的地址即可。

希望问题能早点解决 冬至快乐 ❄️⛄️

**Comment by crisiscain** [comment]
@kaeyleo 感谢大佬的支持和分享，博客已成功搭建，主题很棒！祝圣诞快乐

**Comment by VergeDX** [comment]
感谢作者   我也有同样的问题

**Comment by VergeDX** [comment]
的确是路径的问题，Fork下来后将仓库名改为“用户名.github.io”后恢复正常
很喜欢这个主题   感谢作者大大w
