### ISSUE TITLE
页面总是找不到，只能找到一个http://localhost:4000/2017/04/18/hello-jekyll.html，其他新建之后找不到。

### ISSUE THREAD

**Issue by zjgyb** [kaeyleo/jekyll-theme-H2O#35]

**Comment by Ray-Eldath** [comment]
+1...

**Comment by Ray-Eldath** [comment]
已解决。估计是Jekyll不能很好地支持中文域名。
在`config.json`里添加`permalink: /:year/:month/:day/:title.html`就行。

详见：https://github.com/Ray-Eldath/jekyll-theme-H2O/commit/c2b7fdc02f6f24dcf182ca5d80b9cb21ec9b2d47
