### ISSUE TITLE
没有双重代码框但是代码框不见了

### ISSUE THREAD

**Issue by sctop** [kaeyleo/jekyll-theme-H2O#38]
照搬townwang.com 的博客的css和js后（因为他的代码框正常），双重代码框是没有了，但是post的代码框不见了，代码背景没了

**Comment by sctop** [comment]
如果使用两个`就不会出现，这时候的代码框是灰色的。
我要的是黑色的背景。。。

**Comment by yangliangwu** [comment]
我的解决办法是在app.min.css文件的.markdown-body .highlight的这个样式里增加了overflow-x: auto和overflow-y: auto，把网页显示的双滚动条去掉了，内容多的时候才自动显示。

**Comment by gongchunru** [comment]
https://gongchunru.github.io/  在这基础上改了改。
