### ISSUE TITLE
Feature request: 增加搜索框

### ISSUE THREAD

**Issue by virusdefender** [kaeyleo/jekyll-theme-H2O#4]
建议增加搜索框，编译的时候分词生成 json 或者直接链接到搜索引擎`site: example.com`也可以。

**Comment by kaeyleo** [comment]
@virusdefender 已新增文章搜索功能，使用说明见-> [文章搜索](https://github.com/kaeyleo/jekyll-theme-H2O#%E6%96%87%E7%AB%A0%E6%90%9C%E7%B4%A2)
