### ISSUE TITLE
请问如何修改 index.html 中的home-title: 

### ISSUE THREAD

**Issue by SchnappiJoy** [kaeyleo/jekyll-theme-H2O#43]
已解决： 直接修改index 。html 就行  ，但是不要用记事本打开修改  我就是用记事本打开出的错

**Comment by sctop** [comment]
home-title:【空格】【index首页名称】
【空格】处空格，【index首页名称】写首页名称

**Comment by SchnappiJoy** [comment]
谢谢你的回答。但问题没有得到解决。
我是windows环境 更改 .index  需要jekyll build 吗？
![1517534855 1](https://user-images.githubusercontent.com/35953595/35712165-a720d73c-07fb-11e8-9fd6-1f5d87bb9e95.jpg)

![1517534903 1](https://user-images.githubusercontent.com/35953595/35712216-ea30b3a8-07fb-11e8-853d-c11625386ec3.jpg)

**Comment by sctop** [comment]
不需要

**Comment by sctop** [comment]
你修改后push上去就行了

**Comment by sctop** [comment]
jekyll build在windows部署很麻烦的
如果不想干涉主版本建议新建一个测试版本，当测试版本测试好后就push到主版本上去

**Comment by SchnappiJoy** [comment]
我修改 H2O 主题  主目录下的 index.html  文件  然后push 上去  打开博客链接   首页显示不出来  就像我上面截图那样

**Comment by sctop** [comment]
先声明一下，如果你是xxx.github.io/xxx的形式的话，这是行不通的

**Comment by sctop** [comment]
建议买个域名自己试一下
（反正一个域名值不了多少钱【滑稽】）

**Comment by SchnappiJoy** [comment]
域名 + github 搭建网站已经成功了  ，只是想配置一下 首页的信息 。但是昨天修改index的时候  发现了现在这个问题 。具体原因不知道，百度了好多，也没有类似答案。
http://schnappi.top/    你打开这个网址

**Comment by SchnappiJoy** [comment]
https://github.com/SchnappiJoy      你看一看  我不懂前端

**Comment by sctop** [comment]
。。。你加我QQ好友我给你远程一下
2094880085
