### ISSUE TITLE
社交分享的部分出现了奇怪的错误

### ISSUE THREAD

**Issue by nimocat** [kaeyleo/jekyll-theme-H2O#46]
不知怎么的...社交分享功能分享不了，只有微信的部分会出现奇奇怪怪的东西，在脚本里也会出现红色叉叉，不知道发生了什么QAQ，求旁友解答~

顺便自己改的半水墨风主页！求围观求Star！！！！原PO做的是真的屌，在巨人肩膀上又做了一些改动~
nimocat.github.io！！
<img width="917" alt="pic" src="https://user-images.githubusercontent.com/22885633/35957289-d5152650-0cd5-11e8-869c-09bab9cf5000.png">
！！求解答

**Comment by nimocat** [comment]
手机端貌似没问题啦...回去试试PC

**Comment by kaeyleo** [comment]
编辑器里红色波浪线是因为无法识别liquid模板语法造成的。至于分享功能的问题，切换浏览器为调试模式看看有没有报错。
