### ISSUE TITLE
替换logo和favicon后显示不出来

### ISSUE THREAD

**Issue by caiyajing9210** [kaeyleo/jekyll-theme-H2O#49]
我替换了favicon和logo，网页上显示不出来
是还有哪里需要修改吗

**Comment by Ray-Eldath** [comment]
是否修改了文件名或文件后缀？
若是，请同步修改`_config.yml`中的`avatar`项。

**Comment by kaeyleo** [comment]
主题没有提供自定义logo的配置，请自行手动修改。
