### ISSUE TITLE
disqus加载出错

### ISSUE THREAD

**Issue by niuyi1017** [kaeyleo/jekyll-theme-H2O#55]
配置：
![khq l d5 v_c of6pbv 6](https://user-images.githubusercontent.com/30387148/38404420-8896bd54-399c-11e8-8692-b78e1e798830.png)
disqus后台设置：
![ct_t jd7itmvl d 6s2enz3](https://user-images.githubusercontent.com/30387148/38404447-b7f43d1a-399c-11e8-9478-e14081def454.png)
console控制台提示出错：

![nlk7bb zb6axm6edy 9n7 k](https://user-images.githubusercontent.com/30387148/38404470-db68bed8-399c-11e8-9c5f-b643181f0c72.png)
出错代码具体位置：
![m8y 7_v_rb yyr4powxs](https://user-images.githubusercontent.com/30387148/38404472-df3edc68-399c-11e8-8f48-5338daa096db.png)

搞不懂是哪里没有配置好，求指点

**Comment by Ray-Eldath** [comment]
啊...我本地测试没问题啊
![snipaste_2018-04-06_16-27-15](https://user-images.githubusercontent.com/7938763/38410539-6c09eaec-39b7-11e8-974a-f19645c70799.png)

**Comment by sixiong** [comment]
我本地测试也是这个问题。。。

**Comment by kaeyleo** [comment]
@sixiong @niuyi1017 已修复，重新下载即可

**Comment by sixiong** [comment]
谢谢，我在post里面加了个div就可以了
