### ISSUE TITLE
如何在文章中插入视频呢

### ISSUE THREAD

**Issue by joson1** [kaeyleo/jekyll-theme-H2O#57]
- markdown是可以直接将HTML语言写进去的，不知道这个为什么不能 超链接也不行

**Comment by kaeyleo** [comment]
如果有成功运行H2O，试例的[第一篇](https://github.com/kaeyleo/jekyll-theme-H2O/blob/master/_posts/2017-04-18-hello-jekyll.md)文章就有插入视频。
