### ISSUE TITLE
文章背景上的图片加载，不支持使用https的方式。

### ISSUE THREAD

**Issue by lsgggg123** [kaeyleo/jekyll-theme-H2O#58]
绿色的小锁就没了。

**Comment by kaeyleo** [comment]
如果网站是https协议的，请自行修改站内的资源路径协议：

1. 将资源引入形式改成https
2. 使用相对协议，去掉http或https协议头，浏览器能够根据你网站采用的协议来加载文件

请参考 [从 HTTP 到 HTTPS - 网站部署 HTTPS 中需要做的事情](https://tasaid.com/blog/20161006045104.html) ，[如何在https网页中引入http资源](https://segmentfault.com/a/1190000010067659)
