### ISSUE TITLE
how to use code in markdown? 

### ISSUE THREAD

**Issue by Coder-zyq** [kaeyleo/jekyll-theme-H2O#61]
I use ``` code  ```  and it look  not very well.so how can i do this

**Comment by kaeyleo** [comment]
Why look not very well ? 
![image](https://user-images.githubusercontent.com/9447276/39673992-e628abba-5177-11e8-80d1-5fcea1ff985e.png)

**Comment by Coder-zyq** [comment]
look the link   [my blog address](http://cyqiang.top/2018/04/28/systemHW5.html)
the code writed by markdown as 
first ```
followed by 
/*==============================================================*/
/* DBMS name:      MySQL 5.0                                    */
/* Created on:     2018/5/6 9:56:51                             */
/*==============================================================*/


and end with ```
and it looks ugly in right side.
