### ISSUE TITLE
手机端显示长链接问题

### ISSUE THREAD

**Issue by tea9** [kaeyleo/jekyll-theme-H2O#68]
![c1564d8e240218534ec48f270529e054](https://user-images.githubusercontent.com/39117901/41824064-a248bdcc-783c-11e8-8918-a9d89fcfe837.jpg)

**Comment by Ray-Eldath** [comment]
Will review it later. Thx.

**Comment by kaeyleo** [comment]
给文章摘要部分添加了word-break属性强行断句，已经修复 @tea9
