### ISSUE TITLE
C++高亮问题

### ISSUE THREAD

**Issue by charcai** [kaeyleo/jekyll-theme-H2O#69]
K大好！
有个问题请教一下
CPP在我的博客里不会高亮，希望能支持一下
![Demo](https://s1.ax1x.com/2018/06/27/PiSGX4.png)
![mkd](https://s1.ax1x.com/2018/06/27/PiSrcD.png)
页面地址:[Test](http://blog.charcai.tk/2018/06/27/test.html)
谢谢！

**Comment by charcai** [comment]
另:  
disqus被墙，请问能否帮忙重新配置一个评论系统？

**Comment by weijunzii** [comment]
C++代码高亮可以看看这个下面的回答  
https://github.com/kaeyleo/jekyll-theme-H2O/issues/60
评论可以借鉴这个
https://tea9.github.io/2018/06/24/gitali_config.html

**Comment by charcai** [comment]
抱歉，我用tea9的方法配置了gitalk后还是没有评论框，请问该怎么办？

**Comment by weijunzii** [comment]
这个得问 tea9 了，我刚刚测试了，也是不行

**Comment by Ray-Eldath** [comment]
@charcai 最新版本已经有来必利的评论系统 你可以翻翻commit log 应该有那个PR的merge

若没找到可以看看Ray-Eldath/jeskyll-H2O-theme

**Comment by charcai** [comment]
@tea9 抱歉，评论框不显示
![Pi1vjg.md.png](https://s1.ax1x.com/2018/06/28/Pi1vjg.md.png)]
![code](https://s1.ax1x.com/2018/06/28/Pi1zuQ.png)

**Comment by tea9** [comment]
你好你的js代码 都没有被解释器识别 @charcai 还有
![image](https://user-images.githubusercontent.com/39117901/42037621-74be199c-7b1b-11e8-9b2a-29823bc61948.png)

这个代码没有看到 你可以添加下看看

**Comment by tea9** [comment]
js代码要<script></script> @charcai

**Comment by tea9** [comment]
@charcai  需要帮助吗 我可以帮你远程的

**Comment by charcai** [comment]
等一下，我看看

**Comment by charcai** [comment]
还是有双层代码框的问题，可能还要麻烦大家一下

**Comment by weijunzii** [comment]
感谢 [@tea9](https://github.com/tea9)，成功添加 gitalk 评论，谢谢~

**Comment by tea9** [comment]
不用谢 @weijunzii
