### ISSUE TITLE
一个链接地址错误

### ISSUE THREAD

**Issue by tea9** [kaeyleo/jekyll-theme-H2O#70]
点击第二页 然后在点击右侧的tags 之后会跳转到错误地址

<img width="751" alt="20180629111908" src="https://user-images.githubusercontent.com/39117901/42071596-ab9ea3f0-7b8e-11e8-8865-93238f449023.png">
<img width="282" alt="20180629111929" src="https://user-images.githubusercontent.com/39117901/42071600-b244dc7e-7b8e-11e8-9ebe-ecc3eb57b12e.png">
<img width="818" alt="20180629111958" src="https://user-images.githubusercontent.com/39117901/42071607-b78e6f10-7b8e-11e8-88e3-58a147918cd4.png">

**Comment by tea9** [comment]
为什么你的http://liaokeyu.com/ 没有存在这个问题 是我哪里配置错误了吗？ @kaeyleo

**Comment by weijunzii** [comment]
我的也是这样，可能是之前没有发现，也可能是我最近魔改了。

看了一下也是用这个主题的博客，有些有这种情况，有些没有。

**Comment by tea9** [comment]
@weijunzii  请问你看的那个博客是没有这个问题的？能发给我吗

**Comment by sctop** [comment]
@tea9 毫无问题的访问

**Comment by weijunzii** [comment]
@ tea9 [https://townwang.com/page3/](https://townwang.com/page3/) 这个，你看看。

**Comment by sctop** [comment]
@weijunzii 怎么了，不是好好的吗

**Comment by tea9** [comment]
http://www.zhangqirun.cn/page2/tags.html#%E5%89%8D%E7%AB%AF%E5%BC%80%E5%8F%91

**Comment by weijunzii** [comment]
@sctop [https://townwang.com/page3/](https://townwang.com/page3/)是没有问题的，进去page3，再点击 tag 那里的标签是对的，别的都会出现 404 错误。

意思是我进入了我的 [page2](https://weijunzii.github.io/page2/) ，然后点击右边的标签。如图
![](https://user-images.githubusercontent.com/24533696/42093645-a0376848-7bdf-11e8-94ba-e0b9577f6e8a.png)
正常来说应该是  [https://weijunzii.github.io/tags.html#GitHub](https://weijunzii.github.io/tags.html#GitHub)

可是这里跳转到了 [https://weijunzii.github.io/page2/tags.html#GitHub](https://weijunzii.github.io/page2/tags.html#GitHub)，然后就是 404 了。

**Comment by sctop** [comment]
我去源代码那里看一下解决方案@weijunzii

**Comment by sctop** [comment]
`<a href={{ "tags.html#" | append: tag | pretend: site.baseurl}} class="post-tag">{{ tag }}</a>`
这里的“tag.html#”如果是page2或其它页面，如果不写成“/tag.html#”，则会出错
在index.html

**Comment by weijunzii** [comment]
@sctop 好的~

**Comment by sctop** [comment]
（突然发现我忘记修了另一个bug）

**Comment by tea9** [comment]
作者大概可以把这个问题关闭了
