### ISSUE TITLE
代码框问题

### ISSUE THREAD

**Issue by SunbossRS** [kaeyleo/jekyll-theme-H2O#71]
我的博客的代码框是这样的：
![pic](https://user-images.githubusercontent.com/38691765/42313834-3df323fc-8076-11e8-8842-fca0aff8ef2b.png)
可以解决一下这个问题吗？不知道是不是css样式或者是哪里设置错误了。  
网址：sunbossrs.github.io

**Comment by sctop** [comment]
不知道为什么这个问题在这个主题上总是存在，代码总是不能很好的显示，背景是白色的。
一般情况下重下插件应该没事

**Comment by sctop** [comment]
重下插件我下了很多次，然后就好了。
见好就收，不要追求太多功能，当你实验好可以显示后不要再搞了，否则无限loop

**Comment by SunbossRS** [comment]
哦......

**Comment by tea9** [comment]
偶遇两位11岁的大佬
