### ISSUE TITLE
图标的名称有问题

### ISSUE THREAD

**Issue by cometeme** [kaeyleo/jekyll-theme-H2O#72]
在` _config.yml `这个文件的第50行，写的是dribble，少了一个b

**Comment by cometeme** [comment]
还有一个问题，在个人简介的那一栏，Twitter的图标无法显示

**Comment by tea9** [comment]
![image](https://user-images.githubusercontent.com/39117901/43818571-d2fe9368-9b11-11e8-914e-be80c28c1891.png)
我的可以显示

**Comment by cometeme** [comment]
@tea9 请问一下你是怎么配置的？我的刷不出来

twitter: 'https://twitter.com/cometeme'

<img width="289" alt="2018-08-08 1 56 15" src="https://user-images.githubusercontent.com/22635759/43818791-d9978800-9b12-11e8-85d9-4a5bad81b6c4.png">

**Comment by cometeme** [comment]
加了😂，不知道为啥就是刷不出来

<img width="120" alt="2018-08-08 2 25 04" src="https://user-images.githubusercontent.com/22635759/43819828-e78f0cae-9b16-11e8-89db-a34fc206f93c.png">

**Comment by tea9** [comment]
![image](https://user-images.githubusercontent.com/39117901/43819872-0e6471de-9b17-11e8-96cd-1c930de1f5df.png)
刚刚看了你的博客 可以显示的

**Comment by cometeme** [comment]
😂但是我这里没有，好奇怪啊

**Comment by tea9** [comment]
在刷新下试试

**Comment by cometeme** [comment]
知道了。是浏览器渲染的问题
我mac和ipad的Safari上都显示不出来，但是换成Chrome就显示出来了
这是什么神奇的bug😂

**Comment by tea9** [comment]
![image](https://user-images.githubusercontent.com/39117901/43824167-d5cfb07e-9b23-11e8-947c-25e0812409bd.png)
或许你可以清除下浏览器缓存在试试

**Comment by cometeme** [comment]
试过清缓存了，应该就是浏览器的锅。因为我ipad之前也没有打开过这个网页
