### ISSUE TITLE
add new icon

### ISSUE THREAD

**Issue by Manikhin-KM** [kaeyleo/jekyll-theme-H2O#74]
Thanks for the great topic for jekyll! How can I add a social icon? network vk.com?

**Comment by Manikhin-KM** [comment]
And I also would like the icon youtube.com. How are the icons implemented? Is this your iconfont or someone else's?

**Comment by kaeyleo** [comment]
@Manikhin-KM I used http://www.iconfont.cn and have added the vk icon.
