### ISSUE TITLE
設定方面幾個問題，懇請解答

### ISSUE THREAD

**Issue by iamrToday** [kaeyleo/jekyll-theme-H2O#76]
請教一下
這是我的[_config.yml設定檔](https://github.com/iamrToday/iamrToday.github.io/blob/master/_config.yml)
以下是我遇到的問題

1. Comments的部份，按照您的設定，文章底部還是沒有出現disqus

```
# Comments 评论功能
#comments:
disqus: true
disqus_url: 'https://iamrtoday.disqus.com/embed.js'
```

2. share怪怪的，我只設定三個，但是卻全部的 share 都出現

```
# Share
social-share: true
social-share-items: ["Facebook","Google+","twitter"]
```

3. search無效，我只有設定true，我看Demo似乎也是沒有反應

```
# Search
search: true
```

4. github-markdown.css
我應該要做什麼設定才能夠改底色，文章背景白色太亮了

5. postPatterns 設定後沒有反應

6. RSS設定true後，不知道訂閱按鈕在哪裡

7. markdown TOC部分，我應該怎麼樣讓他顯示出來呢？我試過[gh-md-toc](https://github.com/ekalinin/github-markdown-toc)，還是無法辦到

**Comment by kaeyleo** [comment]
1. 這是個Bug，已經修復了

2. 可以看shareJs插件的[源代碼部分](https://github.com/overtrue/share.js/blob/master/src/js/social-share.js#L62)，正確的寫法是 ['facebook', 'google', 'twitter']

3. search數據是在 `jekyll serve` 執行後自動生成的search.json文件裡，search沒有反應，重新執行 `jekyll server` 命令即可

4. 想要修改文章頁面的背景顏色修改 `dev/sass/common.scss` 中的 .post-content 背景色就行了，開發前記得看[自定義H2O代碼](https://github.com/kaeyleo/jekyll-theme-H2O#%E8%87%AA%E5%AE%9A%E4%B9%89)

5. 修改 `_config.yml` 文件後記得要重啓服務 `jekyll server`

6. 待答...

7. 目前產品處於穩定階段，暫不考慮new feature的pr。呃，至於toc的使用問題還是看插件的文檔吧..我也沒用過
