### ISSUE TITLE
关于导航栏的问题

### ISSUE THREAD

**Issue by fjqisba** [kaeyleo/jekyll-theme-H2O#78]
界面挺不错的,但是导航栏只有HOME和TAG两个按钮额...
剩下的要自己开发吗?

**Comment by kaeyleo** [comment]
还需要哪些功能？

**Comment by fjqisba** [comment]
额,和一般的博客主稍微有点不一样，我写博客是为了记录一些过程和知识.
其中知识非常广泛,所以有很多分类,我以前的博客目录分类就有20多个,光靠标签无法一目了然地看到我曾经写的文章,可以参考一下网易博客的目录分类功能

**Comment by fjqisba** [comment]
原来你这个是按标签进行文章分类的啊,额其实还行,就是与目录分类相比,少了一点那种直观的感觉.

**Comment by kaeyleo** [comment]
也可以把标签当成分类来用，只给文章一个标签就行了

**Comment by fjqisba** [comment]
恩,习惯了那种目录分类,一目了然的感觉,试试这种标签分类好了
