### ISSUE TITLE
手机和电脑不能自适应文章内容

### ISSUE THREAD

**Issue by linchupeng** [kaeyleo/jekyll-theme-H2O#8]
测试时候 发现手机和电脑均不能自适应文章内容

**Comment by kaeyleo** [comment]
整套主题都做了自适应处理，不是很清楚你问题的具体情况。

**Comment by linchupeng** [comment]
控制台提示这样的错误     "NetworkError: 404 Not Found - http://www.****.me/%E7%94%9F%E6%B4%BB/2017/08/03/assets/js/prism.js"
  另外楼主有之前没有侧边栏的版本吗   我更喜欢那个

**Comment by kaeyleo** [comment]
根据错误提示说明引入的文件有错误，是配置文件_config.yml中baseurl参数问题。考虑到展示博主信息和文章搜索功能的必要性，侧边栏就没做自定义隐藏显示了。不过在移动设备访问的时候，侧边栏是会被隐藏的。其实目前这套主题个性化配置我觉得也不少了，最近还增加了夜间模式。其他的配置可以看看说明文档。

**Comment by linchupeng** [comment]
能够正常显示了   但是还是遇到了一点问题  已经发到你邮箱了  感谢作者  感谢开源！！！
