### ISSUE TITLE
你的博客bug

### ISSUE THREAD

**Issue by forezp** [kaeyleo/jekyll-theme-H2O#81]
到文章详情页面，点击个人头像，跳转locahost:4000。另外，在文章详情页可以加侧边栏吗，你这个项目很好，持续关注，介意加下微信聊下吗，我的微信号miles02

**Comment by kaeyleo** [comment]
A1: 文章详情页的个人头像并不支持点击，我试了下没复现你遇到的问题
A2: 考虑到阅读体验，所以没有在文章页面增加其他模块来分散读者的注意力。当然，作为模板要保持对功能抽象，所以无法满足更多的个性化需求。如果坚持要在文章详情页可以加侧边栏，可能需要在个人项目自己改了

**Comment by forezp** [comment]
这是你网页的文章详情的代码片段：
<span class="post-meta-item"><i class="iconfont icon-author"></i><a href="http://localhost:4000" target="_blank" rel="author">廖柯宇</a></span>

**Comment by forezp** [comment]
> <span class="post-meta-item"><i class="iconfont icon-author"></i><a href="http://localhost:4000" target="_blank" rel="author">廖柯宇</a></span>

**Comment by forezp** [comment]
`<span class="post-meta-item"><i class="iconfont icon-author"></i><a href="http://localhost:4000" target="_blank" rel="author">廖柯宇</a></span>`

**Comment by kaeyleo** [comment]
已经解决了
