### ISSUE TITLE
博客文章尾部头像链接是否应当修改？

### ISSUE THREAD

**Issue by Sciroccogti** [kaeyleo/jekyll-theme-H2O#84]
![post.html](https://github.com/kaeyleo/jekyll-theme-H2O/blob/master/_layouts/post.html)中avatar使用了绝对路径，这使得像我这样使用github.io的就会无法显示头像。

是不是可以提示一下，如果代码是推送到服务器而不是在服务器上直接写的应当注意？

**Comment by dyzsoft** [comment]
不影响吧？ 设置 url 和base url就可以了啊

url: 'http://xxx.github.io ' # your host

# if you don't need baseurl, you should leave this value blank.

baseurl: '/blog'
