### ISSUE TITLE
markdown文件里面的链接在博文中点击之后去的是404界面

### ISSUE THREAD

**Issue by YBFJ** [kaeyleo/jekyll-theme-H2O#87]
hi，我很喜欢你的博客主题，但是我最近发现我写的博文里面加的链接在博客中打不开
```
[Mongoose 学习参考文档——基础篇]("https://cnodejs.org/topic/504b4924e2b84515770103dd")
```
这个是正常的网址，但是在博客中的博文点不开

**Comment by kaeyleo** [comment]
[Mongoose 学习参考文档——基础篇](https://cnodejs.org/topic/504b4924e2b84515770103dd)
