### ISSUE TITLE
package-lock.json等文件可否更新

### ISSUE THREAD

**Issue by charcai** [kaeyleo/jekyll-theme-H2O#88]
最近GitHub总是向我发送邮件，提示依赖的包可以更新，但是本萌新不会。。。望大佬相助，帮忙更新一下！谢谢！

**Comment by kaeyleo** [comment]
删掉 `package-lock.json`, `node_modules` ，再重新 `npm install` 试试

https://stackoverflow.com/questions/50328324/how-to-update-package-lock-json
