### ISSUE TITLE
编码问题

### ISSUE THREAD

**Issue by ulink-el** [kaeyleo/jekyll-theme-H2O#9]
clone到本地 运行jekyll serve 后出错，错误如下：

> jekyll 3.5.1 | Error:  incompatible character encodings: UTF-8 and GBK

**Comment by kaeyleo** [comment]
1. 先试试在_config.yml设置encoding: 'utf-8'，各个文件保证是无BOM的UTF-8
2. 参考《Jekyll在Windows下面中文编码问题解决方案》 http://www.ithao123.cn/content-3252162.html

**Comment by Ja50n** [comment]
修改了_config.yml还是不行，已经查看了所有的文件都是无BOM的UTF-8
