### ISSUE TITLE
如何在侧边栏添加自己的微信二维码呢？

### ISSUE THREAD

**Issue by molakirlee** [kaeyleo/jekyll-theme-H2O#94]
请问如何在侧边栏添加自己的微信二维码呢？
谢谢

**Comment by molakirlee** [comment]
比如如何在个人照片之外增加一张图片用来放二维码

**Comment by kaeyleo** [comment]
需要自己加了

**Comment by molakirlee** [comment]
> 需要自己加了

请问要在哪个文件里面添加呢？没有找到添加的位置，希望在个人照片附近，是在index文件里修改吗？
谢谢

**Comment by kaeyleo** [comment]
[ss](https://github.com/kaeyleo/jekyll-theme-H2O#%E8%87%AA%E5%AE%9A%E4%B9%89)
