### ISSUE TITLE
博客首頁和文章頁都正常，但翻頁的時候主題出不來

### ISSUE THREAD

**Issue by bobby285271** [kaeyleo/jekyll-theme-H2O#96]
可以重現

**Comment by bobby285271** [comment]
另外 404 頁面類似，直接訪問 https://bobby285271.github.io/404 正常，但訪問 https://bobby285271.github.io/404/ 也是出不了主題（多了一 /）
在手機瀏覽器下可以復現，沒在電腦上試過

**Comment by bobby285271** [comment]
利用 https://github.com/541435721/541435721.github.io 的 Fork 测试没有问题，说明这个问题是后来才出现的

**Comment by kaeyleo** [comment]
@bobby285271 应该是baseurl的问题，等我再排查一下

**Comment by bobby285271** [comment]
对了 header-img 也出现了无法显示的问题，问题应该出在一个地方

**Comment by BhuZha** [comment]
改变 | Change  `_includes/head.html`
```
    <link rel="stylesheet" href="./assets/css/github-markdown.css">
    <link rel="stylesheet" href="./assets/css/prism.css">
    <link rel="stylesheet" href="./assets/css/share.min.css">
    <link rel="stylesheet" href="./assets/css/app.min.css">
```
到 | To
```
    <link rel="stylesheet" href="/assets/css/github-markdown.css">
    <link rel="stylesheet" href="/assets/css/prism.css">
    <link rel="stylesheet" href="/assets/css/share.min.css">
    <link rel="stylesheet" href="/assets/css/app.min.css">
```
Fixes the issue with missing css on /page2 
@kaeyleo / @bobby285271

**Comment by bobby285271** [comment]
已经解决

**Comment by bobby285271** [comment]
@kaeyleo 抱歉，发现代码框又会出现两个滚动条的问题...
![2018-11-25 17-00-20](https://user-images.githubusercontent.com/20080233/48977356-9eee8e80-f0d3-11e8-8739-7889ee5d11ae.png)
 https://www.bobby285271.top/2018/08/27/nixos-configuration.html

**Comment by kaeyleo** [comment]
我在Mac上暂时无法复现滚动条的问题

**Comment by kaeyleo** [comment]
@bobby285271 我打算建个群，大家沟通会方便点，发你邮箱了。
