### ISSUE TITLE
代码框出现两个滚动条的问题...

### ISSUE THREAD

**Issue by bobby285271** [kaeyleo/jekyll-theme-H2O#99]
![2018-11-25 17-00-20](https://user-images.githubusercontent.com/20080233/48977356-9eee8e80-f0d3-11e8-8739-7889ee5d11ae.png)
https://www.bobby285271.top/2018/08/27/nixos-configuration.html

_Originally posted by @bobby285271 in https://github.com/kaeyleo/jekyll-theme-H2O/issues/96#issuecomment-441425471_

**Comment by bobby285271** [comment]
@kaeyleo 在 midori 和 手机 firefox 下测试没有类似问题，但 midori 并没有显示滚动条，而是直接折行显示
清理了缓存后在电脑版火狐 63 下可以在我的博客和你的博客复现这个问题
可能需要更多测试

**Comment by bobby285271** [comment]
我去贴吧求测试看看能不能复现，似乎得到了不少解决方案，供参考：
http://tieba.baidu.com/p/5960520216

**Comment by 7ippo** [comment]
<pre><code class="language-python"></code></pre>

**Comment by 7ippo** [comment]
<pre><pre><code class="language-python"></code></pre> 代码用这个框起来就没有两个滚动条了</pre>

**Comment by bobby285271** [comment]
相关 issue： #91
